#!/data/data/com.termux/files/usr/bin/bash
# Guided first-run setup for a freshly cloned bridge on Termux.
set -euo pipefail

BRIDGE_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
ENV_FILE="$BRIDGE_DIR/.env"
MODE="${1:-}"

usage() {
  cat <<'EOF'
用法：./setup.sh [--check|--no-start]

  （无参数）  安装 Python 依赖、引导填写 .env，并启动服务。
  --no-start  完成检查和配置，但不启动服务。
  --check     只检查本机依赖、配置和服务状态，不修改任何内容。
EOF
}

say() { printf '\n==> %s\n' "$*"; }
fail() { printf '错误：%s\n' "$*" >&2; exit 1; }

if [[ "$MODE" == "-h" || "$MODE" == "--help" ]]; then
  usage
  exit 0
fi
if [[ -n "$MODE" && "$MODE" != "--check" && "$MODE" != "--no-start" ]]; then
  usage
  exit 2
fi

check_python() {
  if command -v python >/dev/null 2>&1; then
    return
  fi
  if [[ "$MODE" == "--check" ]]; then
    fail "未找到 python；请在 Termux 中执行 pkg install python"
  fi
  command -v pkg >/dev/null 2>&1 || fail "未找到 pkg；请在 Termux 环境运行本脚本"
  say "正在安装 Termux Python"
  pkg install -y python
}

check_codex() {
  if command -v codex >/dev/null 2>&1; then
    return
  fi
  cat >&2 <<'EOF'
错误：未找到 Codex CLI。

请先按官方 Codex CLI 安装与登录流程完成本机配置，确保下面命令能成功执行后再重新运行本脚本：
  codex --version
  codex app-server
EOF
  exit 1
}

config_present() {
  [[ -f "$ENV_FILE" ]] || return 1
  # Use the same shell parsing model as start.sh, but never print values.
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
  [[ -n "${FEISHU_APP_ID:-}" && -n "${FEISHU_APP_SECRET:-}" && -n "${CODEX_BRIDGE_CWD:-}" && -n "${CODEX_WORKSPACE_ROOT:-}" ]]
}

write_config() {
  local app_id app_secret allowed cwd workspace_root
  say "首次配置飞书机器人"
  printf '飞书 App ID（例如 cli_xxx）：'
  read -r app_id
  [[ -n "$app_id" ]] || fail "App ID 不能为空"
  printf '飞书 App Secret（输入不回显）：'
  read -r -s app_secret
  printf '\n'
  [[ -n "$app_secret" ]] || fail "App Secret 不能为空"
  printf '允许使用的飞书 open_id（多个用逗号分隔；留空=任何能私聊机器人的人）：'
  read -r allowed
  printf 'Codex 工作目录 [%s]：' "$(pwd -P)"
  read -r cwd
  cwd="${cwd:-$(pwd -P)}"
  [[ -d "$cwd" ]] || fail "工作目录不存在：$cwd"
  cwd="$(CDPATH= cd -- "$cwd" && pwd -P)"
  printf '允许切换的工作区根目录 [%s]：' "$(dirname -- "$cwd")"
  read -r workspace_root
  workspace_root="${workspace_root:-$(dirname -- "$cwd")}"
  [[ -d "$workspace_root" ]] || fail "工作区根目录不存在：$workspace_root"
  workspace_root="$(CDPATH= cd -- "$workspace_root" && pwd -P)"
  [[ "$cwd" == "$workspace_root" || "$cwd" == "$workspace_root"/* ]] || fail "Codex 工作目录必须位于工作区根目录内"

  umask 077
  {
    printf '# Generated by setup.sh. Keep this file private.\n'
    printf 'FEISHU_APP_ID=%q\n' "$app_id"
    printf 'FEISHU_APP_SECRET=%q\n' "$app_secret"
    printf 'FEISHU_ALLOWED_OPEN_IDS=%q\n' "$allowed"
    printf 'CODEX_BRIDGE_CWD=%q\n' "$cwd"
    printf 'CODEX_WORKSPACE_ROOT=%q\n' "$workspace_root"
    printf 'CODEX_MODEL=\n'
    printf 'CODEX_APP_SERVER=%q\n' 'codex app-server'
    printf 'CODEX_MAX_ATTACHMENT_BYTES=20971520\n'
    printf 'CODEX_APPROVAL_TIMEOUT_SECONDS=600\n'
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  say "已创建受保护配置：$ENV_FILE"
}

check_python
check_codex

if [[ "$MODE" == "--check" ]]; then
  say "Python: $(python --version 2>&1)"
  say "Codex: $(codex --version 2>&1)"
  # Avoid importing the full SDK here: on a fresh Termux install that can spend
  # a long time compiling bytecode, while package metadata is enough to tell
  # the user whether setup installed both required distributions.
  python -c 'from importlib.metadata import version; version("httpx"); version("lark-oapi")' \
    || fail "缺少 Python 依赖；请执行 ./setup.sh"
  config_present || fail "配置不完整；已有部署请在 .env 中补充 CODEX_WORKSPACE_ROOT，再重新检查"
  say "配置：已找到 .env（不会显示凭据）"
  "$BRIDGE_DIR/start.sh" status
  exit 0
fi

say "安装或校验 Python 依赖"
python -m pip install -r "$BRIDGE_DIR/requirements.txt"

if [[ ! -f "$ENV_FILE" ]]; then
  write_config
elif ! config_present; then
  fail ".env 已存在但配置不完整；请补充 CODEX_WORKSPACE_ROOT（且须包含 CODEX_BRIDGE_CWD），或手动删除后重新执行 ./setup.sh"
else
  say "检测到已有 .env，保留现有配置"
fi

if [[ "$MODE" == "--no-start" ]]; then
  say "配置完成。随后可执行：$BRIDGE_DIR/start.sh start"
  exit 0
fi

say "启动飞书 Codex Bridge"
"$BRIDGE_DIR/start.sh" start
"$BRIDGE_DIR/start.sh" status
printf '\n完成。请在飞书私聊机器人发送 /help。\n'
